# Usamos una imagen ligera de Python
FROM python:3.12-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /code

# Copiamos primero el archivo de dependencias para aprovechar el caché de Docker
COPY ./requirements.txt /code/requirements.txt

# Instalamos las dependencias
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copiamos todo el código de nuestra API (la carpeta 'app') al contenedor
COPY ./app /code/app

# Exponemos el puerto interno de FastAPI
EXPOSE 8000

# Comando maestro para levantar el servidor de Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]